# examen-1b-freire-alex

# 2

In [4]:
import numpy as np
from scipy import ndimage
from scipy import misc

In [6]:
np.zeros((10))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 3

In [11]:
b=np.zeros((10))

In [12]:
b[5]=1

In [13]:
b

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

# 4

In [9]:
a=np.arange((50))

In [10]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [12]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

# 5

In [9]:
np.arange((9)).reshape(1,3,3)

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

# 6

In [14]:
arreglo=[1,2,0,0,4,0]

In [16]:
for elemento in arreglo:
    if elemento != 0:
        print(f"indice: {arreglo.index(elemento)}")

indice: 0
indice: 1
indice: 4

# 7

In [18]:
np.eye((3))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 8

In [22]:
np.random.random((3,3,3))

array([[[0.07275231, 0.69967573, 0.79175486],
        [0.56398613, 0.73304044, 0.3287647 ],
        [0.35525285, 0.61876937, 0.77954519]],

       [[0.06926685, 0.85092223, 0.6077218 ],
        [0.41597545, 0.59137683, 0.58533853],
        [0.26490519, 0.56320206, 0.45204265]],

       [[0.7385294 , 0.16354243, 0.11881454],
        [0.91996774, 0.18771322, 0.99131203],
        [0.32502391, 0.0673809 , 0.85140765]]])

# 9

In [27]:
d=np.random.random((10,10))

In [28]:
d

array([[0.10393491, 0.04708212, 0.42384448, 0.15918893, 0.25052629,
        0.03807538, 0.65896047, 0.52593366, 0.64827076, 0.70173537],
       [0.44299659, 0.08391342, 0.09930273, 0.76005049, 0.94588895,
        0.94334996, 0.78684544, 0.28019393, 0.91421445, 0.0472033 ],
       [0.67487221, 0.62076284, 0.54681724, 0.23764571, 0.41003359,
        0.82884474, 0.55417204, 0.81974044, 0.27568835, 0.57401394],
       [0.61297817, 0.51409916, 0.53933847, 0.0584554 , 0.6814824 ,
        0.93635242, 0.248627  , 0.81202034, 0.49472827, 0.51007667],
       [0.98684927, 0.20707789, 0.0322784 , 0.416914  , 0.87606682,
        0.18799983, 0.65526746, 0.27984958, 0.76610325, 0.95374494],
       [0.11047362, 0.94805409, 0.77071455, 0.8865555 , 0.98431524,
        0.30153726, 0.57535698, 0.47379028, 0.20958835, 0.28463085],
       [0.40140993, 0.14786222, 0.54601433, 0.78714649, 0.16810464,
        0.77472418, 0.94460252, 0.34866921, 0.89523914, 0.73848493],
       [0.89849567, 0.78612555, 0.16739271, 0.62279555, 0.80783799,
        0.288572  , 0.05151149, 0.42123842, 0.4912058 , 0.96010809],
       [0.79040325, 0.93643356, 0.98667646, 0.62634618, 0.39922837,
        0.70138863, 0.5856281 , 0.8851708 , 0.99570675, 0.38295459],
       [0.594448  , 0.39365687, 0.44100489, 0.3443296 , 0.73040617,
        0.23143788, 0.28611195, 0.05415396, 0.09398706, 0.24495728]])

In [32]:
print(f"valor maximo:{max(item[2] for item in d)}")

valor maximo:0.9866764592420881

In [33]:
print(f"valor minimo:{min(item[2] for item in d)}")

valor minimo:0.03227839528908216

# 10

In [35]:
get_spaced_colors(5)

[(0, 0, 0), (50, 154, 51), (101, 52, 102), (151, 206, 153), (202, 104, 204)]

In [39]:
mapache=misc.face()

In [40]:
mapache

array([[[121, 112, 131],
        [138, 129, 148],
        [153, 144, 165],
        ...,
        [119, 126,  74],
        [131, 136,  82],
        [139, 144,  90]],

       [[ 89,  82, 100],
        [110, 103, 121],
        [130, 122, 143],
        ...,
        [118, 125,  71],
        [134, 141,  87],
        [146, 153,  99]],

       [[ 73,  66,  84],
        [ 94,  87, 105],
        [115, 108, 126],
        ...,
        [117, 126,  71],
        [133, 142,  87],
        [144, 153,  98]],

       ...,

       [[ 87, 106,  76],
        [ 94, 110,  81],
        [107, 124,  92],
        ...,
        [120, 158,  97],
        [119, 157,  96],
        [119, 158,  95]],

       [[ 85, 101,  72],
        [ 95, 111,  82],
        [112, 127,  96],
        ...,
        [121, 157,  96],
        [120, 156,  94],
        [120, 156,  94]],

       [[ 85, 101,  74],
        [ 97, 113,  84],
        [111, 126,  97],
        ...,
        [120, 156,  95],
        [119, 155,  93],
        [118, 154,  92]]], dtype=uint8)

In [51]:
def get_different_colors(n):
    max_value = 16581375 
    interval = int(max_value / n)
    colors = [hex(I)[2:].zfill(6) for I in range(0, max_value, interval)]
    
    return [(int(i[:2], 16), int(i[2:4], 16), int(i[4:], 16)) for i in colors]

In [44]:
len(mapache)

768

In [52]:
get_different_colors(len(mapache))

[(0, 0, 0),
 (0, 84, 86),
 (0, 168, 172),
 (0, 253, 2),
 (1, 81, 88),
 (1, 165, 174),
 (1, 250, 4),
 (2, 78, 90),
 (2, 162, 176),
 (2, 247, 6),
 (3, 75, 92),
 (3, 159, 178),
 (3, 244, 8),
 (4, 72, 94),
 (4, 156, 180),
 (4, 241, 10),
 (5, 69, 96),
 (5, 153, 182),
 (5, 238, 12),
 (6, 66, 98),
 (6, 150, 184),
 (6, 235, 14),
 (7, 63, 100),
 (7, 147, 186),
 (7, 232, 16),
 (8, 60, 102),
 (8, 144, 188),
 (8, 229, 18),
 (9, 57, 104),
 (9, 141, 190),
 (9, 226, 20),
 (10, 54, 106),
 (10, 138, 192),
 (10, 223, 22),
 (11, 51, 108),
 (11, 135, 194),
 (11, 220, 24),
 (12, 48, 110),
 (12, 132, 196),
 (12, 217, 26),
 (13, 45, 112),
 (13, 129, 198),
 (13, 214, 28),
 (14, 42, 114),
 (14, 126, 200),
 (14, 211, 30),
 (15, 39, 116),
 (15, 123, 202),
 (15, 208, 32),
 (16, 36, 118),
 (16, 120, 204),
 (16, 205, 34),
 (17, 33, 120),
 (17, 117, 206),
 (17, 202, 36),
 (18, 30, 122),
 (18, 114, 208),
 (18, 199, 38),
 (19, 27, 124),
 (19, 111, 210),
 (19, 196, 40),
 (20, 24, 126),
 (20, 108, 212),
 (20, 193, 42),
 (21, 21, 128),
 (21, 105, 214),
 (21, 190, 44),
 (22, 18, 130),
 (22, 102, 216),
 (22, 187, 46),
 (23, 15, 132),
 (23, 99, 218),
 (23, 184, 48),
 (24, 12, 134),
 (24, 96, 220),
 (24, 181, 50),
 (25, 9, 136),
 (25, 93, 222),
 (25, 178, 52),
 (26, 6, 138),
 (26, 90, 224),
 (26, 175, 54),
 (27, 3, 140),
 (27, 87, 226),
 (27, 172, 56),
 (28, 0, 142),
 (28, 84, 228),
 (28, 169, 58),
 (28, 253, 144),
 (29, 81, 230),
 (29, 166, 60),
 (29, 250, 146),
 (30, 78, 232),
 (30, 163, 62),
 (30, 247, 148),
 (31, 75, 234),
 (31, 160, 64),
 (31, 244, 150),
 (32, 72, 236),
 (32, 157, 66),
 (32, 241, 152),
 (33, 69, 238),
 (33, 154, 68),
 (33, 238, 154),
 (34, 66, 240),
 (34, 151, 70),
 (34, 235, 156),
 (35, 63, 242),
 (35, 148, 72),
 (35, 232, 158),
 (36, 60, 244),
 (36, 145, 74),
 (36, 229, 160),
 (37, 57, 246),
 (37, 142, 76),
 (37, 226, 162),
 (38, 54, 248),
 (38, 139, 78),
 (38, 223, 164),
 (39, 51, 250),
 (39, 136, 80),
 (39, 220, 166),
 (40, 48, 252),
 (40, 133, 82),
 (40, 217, 168),
 (41, 45, 254),
 (41, 130, 84),
 (41, 214, 170),
 (42, 43, 0),
 (42, 127, 86),
 (42, 211, 172),
 (43, 40, 2),
 (43, 124, 88),
 (43, 208, 174),
 (44, 37, 4),
 (44, 121, 90),
 (44, 205, 176),
 (45, 34, 6),
 (45, 118, 92),
 (45, 202, 178),
 (46, 31, 8),
 (46, 115, 94),
 (46, 199, 180),
 (47, 28, 10),
 (47, 112, 96),
 (47, 196, 182),
 (48, 25, 12),
 (48, 109, 98),
 (48, 193, 184),
 (49, 22, 14),
 (49, 106, 100),
 (49, 190, 186),
 (50, 19, 16),
 (50, 103, 102),
 (50, 187, 188),
 (51, 16, 18),
 (51, 100, 104),
 (51, 184, 190),
 (52, 13, 20),
 (52, 97, 106),
 (52, 181, 192),
 (53, 10, 22),
 (53, 94, 108),
 (53, 178, 194),
 (54, 7, 24),
 (54, 91, 110),
 (54, 175, 196),
 (55, 4, 26),
 (55, 88, 112),
 (55, 172, 198),
 (56, 1, 28),
 (56, 85, 114),
 (56, 169, 200),
 (56, 254, 30),
 (57, 82, 116),
 (57, 166, 202),
 (57, 251, 32),
 (58, 79, 118),
 (58, 163, 204),
 (58, 248, 34),
 (59, 76, 120),
 (59, 160, 206),
 (59, 245, 36),
 (60, 73, 122),
 (60, 157, 208),
 (60, 242, 38),
 (61, 70, 124),
 (61, 154, 210),
 (61, 239, 40),
 (62, 67, 126),
 (62, 151, 212),
 (62, 236, 42),
 (63, 64, 128),
 (63, 148, 214),
 (63, 233, 44),
 (64, 61, 130),
 (64, 145, 216),
 (64, 230, 46),
 (65, 58, 132),
 (65, 142, 218),
 (65, 227, 48),
 (66, 55, 134),
 (66, 139, 220),
 (66, 224, 50),
 (67, 52, 136),
 (67, 136, 222),
 (67, 221, 52),
 (68, 49, 138),
 (68, 133, 224),
 (68, 218, 54),
 (69, 46, 140),
 (69, 130, 226),
 (69, 215, 56),
 (70, 43, 142),
 (70, 127, 228),
 (70, 212, 58),
 (71, 40, 144),
 (71, 124, 230),
 (71, 209, 60),
 (72, 37, 146),
 (72, 121, 232),
 (72, 206, 62),
 (73, 34, 148),
 (73, 118, 234),
 (73, 203, 64),
 (74, 31, 150),
 (74, 115, 236),
 (74, 200, 66),
 (75, 28, 152),
 (75, 112, 238),
 (75, 197, 68),
 (76, 25, 154),
 (76, 109, 240),
 (76, 194, 70),
 (77, 22, 156),
 (77, 106, 242),
 (77, 191, 72),
 (78, 19, 158),
 (78, 103, 244),
 (78, 188, 74),
 (79, 16, 160),
 (79, 100, 246),
 (79, 185, 76),
 (80, 13, 162),
 (80, 97, 248),
 (80, 182, 78),
 (81, 10, 164),
 (81, 94, 250),
 (81, 179, 80),
 (82, 7, 166),
 (82, 91, 252),
 (82, 176, 82),
 (83, 4, 168),
 (83, 88, 254),
 (83, 173, 84),
 (84, 1, 170),
 (84, 86, 0),
 (84, 170, 86),
 (84, 254, 172),
 (85, 83, 2),
 (85, 167, 88),
 (85, 251, 174),
 (86, 80, 4),
 (86, 164, 90),
 (86, 248, 176),
 (87, 77, 6),
 (87, 161, 92),
 (87, 245, 178),
 (88, 74, 8),
 (88, 158, 94),
 (88, 242, 180),
 (89, 71, 10),
 (89, 155, 96),
 (89, 239, 182),
 (90, 68, 12),
 (90, 152, 98),
 (90, 236, 184),
 (91, 65, 14),
 (91, 149, 100),
 (91, 233, 186),
 (92, 62, 16),
 (92, 146, 102),
 (92, 230, 188),
 (93, 59, 18),
 (93, 143, 104),
 (93, 227, 190),
 (94, 56, 20),
 (94, 140, 106),
 (94, 224, 192),
 (95, 53, 22),
 (95, 137, 108),
 (95, 221, 194),
 (96, 50, 24),
 (96, 134, 110),
 (96, 218, 196),
 (97, 47, 26),
 (97, 131, 112),
 (97, 215, 198),
 (98, 44, 28),
 (98, 128, 114),
 (98, 212, 200),
 (99, 41, 30),
 (99, 125, 116),
 (99, 209, 202),
 (100, 38, 32),
 (100, 122, 118),
 (100, 206, 204),
 (101, 35, 34),
 (101, 119, 120),
 (101, 203, 206),
 (102, 32, 36),
 (102, 116, 122),
 (102, 200, 208),
 (103, 29, 38),
 (103, 113, 124),
 (103, 197, 210),
 (104, 26, 40),
 (104, 110, 126),
 (104, 194, 212),
 (105, 23, 42),
 (105, 107, 128),
 (105, 191, 214),
 (106, 20, 44),
 (106, 104, 130),
 (106, 188, 216),
 (107, 17, 46),
 (107, 101, 132),
 (107, 185, 218),
 (108, 14, 48),
 (108, 98, 134),
 (108, 182, 220),
 (109, 11, 50),
 (109, 95, 136),
 (109, 179, 222),
 (110, 8, 52),
 (110, 92, 138),
 (110, 176, 224),
 (111, 5, 54),
 (111, 89, 140),
 (111, 173, 226),
 (112, 2, 56),
 (112, 86, 142),
 (112, 170, 228),
 (112, 255, 58),
 (113, 83, 144),
 (113, 167, 230),
 (113, 252, 60),
 (114, 80, 146),
 (114, 164, 232),
 (114, 249, 62),
 (115, 77, 148),
 (115, 161, 234),
 (115, 246, 64),
 (116, 74, 150),
 (116, 158, 236),
 (116, 243, 66),
 (117, 71, 152),
 (117, 155, 238),
 (117, 240, 68),
 (118, 68, 154),
 (118, 152, 240),
 (118, 237, 70),
 (119, 65, 156),
 (119, 149, 242),
 (119, 234, 72),
 (120, 62, 158),
 (120, 146, 244),
 (120, 231, 74),
 (121, 59, 160),
 (121, 143, 246),
 (121, 228, 76),
 (122, 56, 162),
 (122, 140, 248),
 (122, 225, 78),
 (123, 53, 164),
 (123, 137, 250),
 (123, 222, 80),
 (124, 50, 166),
 (124, 134, 252),
 (124, 219, 82),
 (125, 47, 168),
 (125, 131, 254),
 (125, 216, 84),
 (126, 44, 170),
 (126, 129, 0),
 (126, 213, 86),
 (127, 41, 172),
 (127, 126, 2),
 (127, 210, 88),
 (128, 38, 174),
 (128, 123, 4),
 (128, 207, 90),
 (129, 35, 176),
 (129, 120, 6),
 (129, 204, 92),
 (130, 32, 178),
 (130, 117, 8),
 (130, 201, 94),
 (131, 29, 180),
 (131, 114, 10),
 (131, 198, 96),
 (132, 26, 182),
 (132, 111, 12),
 (132, 195, 98),
 (133, 23, 184),
 (133, 108, 14),
 (133, 192, 100),
 (134, 20, 186),
 (134, 105, 16),
 (134, 189, 102),
 (135, 17, 188),
 (135, 102, 18),
 (135, 186, 104),
 (136, 14, 190),
 (136, 99, 20),
 (136, 183, 106),
 (137, 11, 192),
 (137, 96, 22),
 (137, 180, 108),
 (138, 8, 194),
 (138, 93, 24),
 (138, 177, 110),
 (139, 5, 196),
 (139, 90, 26),
 (139, 174, 112),
 (140, 2, 198),
 (140, 87, 28),
 (140, 171, 114),
 (140, 255, 200),
 (141, 84, 30),
 (141, 168, 116),
 (141, 252, 202),
 (142, 81, 32),
 (142, 165, 118),
 (142, 249, 204),
 (143, 78, 34),
 (143, 162, 120),
 (143, 246, 206),
 (144, 75, 36),
 (144, 159, 122),
 (144, 243, 208),
 (145, 72, 38),
 (145, 156, 124),
 (145, 240, 210),
 (146, 69, 40),
 (146, 153, 126),
 (146, 237, 212),
 (147, 66, 42),
 (147, 150, 128),
 (147, 234, 214),
 (148, 63, 44),
 (148, 147, 130),
 (148, 231, 216),
 (149, 60, 46),
 (149, 144, 132),
 (149, 228, 218),
 (150, 57, 48),
 (150, 141, 134),
 (150, 225, 220),
 (151, 54, 50),
 (151, 138, 136),
 (151, 222, 222),
 (152, 51, 52),
 (152, 135, 138),
 (152, 219, 224),
 (153, 48, 54),
 (153, 132, 140),
 (153, 216, 226),
 (154, 45, 56),
 (154, 129, 142),
 (154, 213, 228),
 (155, 42, 58),
 (155, 126, 144),
 (155, 210, 230),
 (156, 39, 60),
 (156, 123, 146),
 (156, 207, 232),
 (157, 36, 62),
 (157, 120, 148),
 (157, 204, 234),
 (158, 33, 64),
 (158, 117, 150),
 (158, 201, 236),
 (159, 30, 66),
 (159, 114, 152),
 (159, 198, 238),
 (160, 27, 68),
 (160, 111, 154),
 (160, 195, 240),
 (161, 24, 70),
 (161, 108, 156),
 (161, 192, 242),
 (162, 21, 72),
 (162, 105, 158),
 (162, 189, 244),
 (163, 18, 74),
 (163, 102, 160),
 (163, 186, 246),
 (164, 15, 76),
 (164, 99, 162),
 (164, 183, 248),
 (165, 12, 78),
 (165, 96, 164),
 (165, 180, 250),
 (166, 9, 80),
 (166, 93, 166),
 (166, 177, 252),
 (167, 6, 82),
 (167, 90, 168),
 (167, 174, 254),
 (168, 3, 84),
 (168, 87, 170),
 (168, 172, 0),
 (169, 0, 86),
 (169, 84, 172),
 (169, 169, 2),
 (169, 253, 88),
 (170, 81, 174),
 (170, 166, 4),
 (170, 250, 90),
 (171, 78, 176),
 (171, 163, 6),
 (171, 247, 92),
 (172, 75, 178),
 (172, 160, 8),
 (172, 244, 94),
 (173, 72, 180),
 (173, 157, 10),
 (173, 241, 96),
 (174, 69, 182),
 (174, 154, 12),
 (174, 238, 98),
 (175, 66, 184),
 (175, 151, 14),
 (175, 235, 100),
 (176, 63, 186),
 (176, 148, 16),
 (176, 232, 102),
 (177, 60, 188),
 (177, 145, 18),
 (177, 229, 104),
 (178, 57, 190),
 (178, 142, 20),
 (178, 226, 106),
 (179, 54, 192),
 (179, 139, 22),
 (179, 223, 108),
 (180, 51, 194),
 (180, 136, 24),
 (180, 220, 110),
 (181, 48, 196),
 (181, 133, 26),
 (181, 217, 112),
 (182, 45, 198),
 (182, 130, 28),
 (182, 214, 114),
 (183, 42, 200),
 (183, 127, 30),
 (183, 211, 116),
 (184, 39, 202),
 (184, 124, 32),
 (184, 208, 118),
 (185, 36, 204),
 (185, 121, 34),
 (185, 205, 120),
 (186, 33, 206),
 (186, 118, 36),
 (186, 202, 122),
 (187, 30, 208),
 (187, 115, 38),
 (187, 199, 124),
 (188, 27, 210),
 (188, 112, 40),
 (188, 196, 126),
 (189, 24, 212),
 (189, 109, 42),
 (189, 193, 128),
 (190, 21, 214),
 (190, 106, 44),
 (190, 190, 130),
 (191, 18, 216),
 (191, 103, 46),
 (191, 187, 132),
 (192, 15, 218),
 (192, 100, 48),
 (192, 184, 134),
 (193, 12, 220),
 (193, 97, 50),
 (193, 181, 136),
 (194, 9, 222),
 (194, 94, 52),
 (194, 178, 138),
 (195, 6, 224),
 (195, 91, 54),
 (195, 175, 140),
 (196, 3, 226),
 (196, 88, 56),
 (196, 172, 142),
 (197, 0, 228),
 (197, 85, 58),
 (197, 169, 144),
 (197, 253, 230),
 (198, 82, 60),
 (198, 166, 146),
 (198, 250, 232),
 (199, 79, 62),
 (199, 163, 148),
 (199, 247, 234),
 (200, 76, 64),
 (200, 160, 150),
 (200, 244, 236),
 (201, 73, 66),
 (201, 157, 152),
 (201, 241, 238),
 (202, 70, 68),
 (202, 154, 154),
 (202, 238, 240),
 (203, 67, 70),
 (203, 151, 156),
 (203, 235, 242),
 (204, 64, 72),
 (204, 148, 158),
 (204, 232, 244),
 (205, 61, 74),
 (205, 145, 160),
 (205, 229, 246),
 (206, 58, 76),
 (206, 142, 162),
 (206, 226, 248),
 (207, 55, 78),
 (207, 139, 164),
 (207, 223, 250),
 (208, 52, 80),
 (208, 136, 166),
 (208, 220, 252),
 (209, 49, 82),
 (209, 133, 168),
 (209, 217, 254),
 (210, 46, 84),
 (210, 130, 170),
 (210, 215, 0),
 (211, 43, 86),
 (211, 127, 172),
 (211, 212, 2),
 (212, 40, 88),
 (212, 124, 174),
 (212, 209, 4),
 (213, 37, 90),
 (213, 121, 176),
 (213, 206, 6),
 (214, 34, 92),
 (214, 118, 178),
 (214, 203, 8),
 (215, 31, 94),
 (215, 115, 180),
 (215, 200, 10),
 (216, 28, 96),
 (216, 112, 182),
 (216, 197, 12),
 (217, 25, 98),
 (217, 109, 184),
 (217, 194, 14),
 (218, 22, 100),
 (218, 106, 186),
 (218, 191, 16),
 (219, 19, 102),
 (219, 103, 188),
 (219, 188, 18),
 (220, 16, 104),
 (220, 100, 190),
 (220, 185, 20),
 (221, 13, 106),
 (221, 97, 192),
 (221, 182, 22),
 (222, 10, 108),
 (222, 94, 194),
 (222, 179, 24),
 (223, 7, 110),
 (223, 91, 196),
 (223, 176, 26),
 (224, 4, 112),
 (224, 88, 198),
 (224, 173, 28),
 (225, 1, 114),
 (225, 85, 200),
 (225, 170, 30),
 (225, 254, 116),
 (226, 82, 202),
 (226, 167, 32),
 (226, 251, 118),
 (227, 79, 204),
 (227, 164, 34),
 (227, 248, 120),
 (228, 76, 206),
 (228, 161, 36),
 (228, 245, 122),
 (229, 73, 208),
 (229, 158, 38),
 (229, 242, 124),
 (230, 70, 210),
 (230, 155, 40),
 (230, 239, 126),
 (231, 67, 212),
 (231, 152, 42),
 (231, 236, 128),
 (232, 64, 214),
 (232, 149, 44),
 (232, 233, 130),
 (233, 61, 216),
 (233, 146, 46),
 (233, 230, 132),
 (234, 58, 218),
 (234, 143, 48),
 (234, 227, 134),
 (235, 55, 220),
 (235, 140, 50),
 (235, 224, 136),
 (236, 52, 222),
 (236, 137, 52),
 (236, 221, 138),
 (237, 49, 224),
 (237, 134, 54),
 (237, 218, 140),
 (238, 46, 226),
 (238, 131, 56),
 (238, 215, 142),
 (239, 43, 228),
 (239, 128, 58),
 (239, 212, 144),
 (240, 40, 230),
 (240, 125, 60),
 (240, 209, 146),
 (241, 37, 232),
 (241, 122, 62),
 (241, 206, 148),
 (242, 34, 234),
 (242, 119, 64),
 (242, 203, 150),
 (243, 31, 236),
 (243, 116, 66),
 (243, 200, 152),
 (244, 28, 238),
 (244, 113, 68),
 (244, 197, 154),
 (245, 25, 240),
 (245, 110, 70),
 (245, 194, 156),
 (246, 22, 242),
 (246, 107, 72),
 (246, 191, 158),
 (247, 19, 244),
 (247, 104, 74),
 (247, 188, 160),
 (248, 16, 246),
 (248, 101, 76),
 (248, 185, 162),
 (249, 13, 248),
 (249, 98, 78),
 (249, 182, 164),
 (250, 10, 250),
 (250, 95, 80),
 (250, 179, 166),
 (251, 7, 252),
 (251, 92, 82),
 (251, 176, 168),
 (252, 4, 254),
 (252, 89, 84),
 (252, 173, 170),
 (253, 2, 0)]

# 11

In [6]:
import pandas as pd
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [54]:
mylist

['a',
 'b',
 'c',
 'e',
 'd',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [57]:
mm=pd.Series(v[0] for v in mylist)

In [61]:
print(f"list to series\n{mm}")

list to series
0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [65]:
myarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25])

In [68]:
mn=pd.Series(myarr)

In [69]:
print(f"array to series\n{mn}")

array to series
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32

In [70]:
print(f"diccionario to series\n{pd.Series(mydict)}")

diccionario to series
a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64

# 12

In [7]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

In [39]:
df = pd.DataFrame({'indice':ser.index,'numero':ser.values})

In [40]:
df

   indice  numero
0       a       0
1       b       1
2       c       2
3       e       3
4       d       4
5       f       5
6       g       6
7       h       7
8       i       8
9       j       9
10      k      10
11      l      11
12      m      12
13      n      13
14      o      14
15      p      15
16      q      16
17      r      17
18      s      18
19      t      19
20      u      20
21      v      21
22      w      22
23      x      23
24      y      24
25      z      25

# 13

In [43]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

In [50]:
df=pd.concat([ser1, ser2],axis=1)

In [51]:
df

    0   1
0   a   0
1   b   1
2   c   2
3   e   3
4   d   4
5   f   5
6   g   6
7   h   7
8   i   8
9   j   9
10  k  10
11  l  11
12  m  12
13  n  13
14  o  14
15  p  15
16  q  16
17  r  17
18  s  18
19  t  19
20  u  20
21  v  21
22  w  22
23  x  23
24  y  24
25  z  25